export default {
  pageBackground: '#f5f8fa',
  primary: '#3097d1',
  danger: '#bf5329',
  tintColor: '#2f95dc',
  tabIconDefault: '#ccc',
  tabIconSelected: '#3097d1',
  tabBar: '#fefefe',
  errorBackground: 'red',
  errorText: '#fff',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: '#3097d1',
  noticeText: '#fff',
}
